#!/bin/bash

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

cd ${OPENSHIFT_REPO_DIR}
java -jar build/libs/javadoc-badge.jar \
  --server.address=${OPENSHIFT_DIY_IP} \
  --server.port=${OPENSHIFT_DIY_PORT} \
  --server.error.whitelabel.enabled=false \
  |& /usr/bin/logshifter &
