version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  # prepend Java entry, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - SET PATH=%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET JAVA_OPTS=-Xmx4g
  - cmd: java -version
  - ./gradlew --version
build_script:
  - ./gradlew --no-search-upward --info clean assemble
test_script:
  - ./gradlew --no-search-upward --info build
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
